<?php

include("qoutes.php"); // inclusion of the auto generated qoutes for winners and loosers.

$message = ""; // message printed on the screen has been declared as empty

$codeQoute=$personalQoute; // personal(favorite programing qoute) as been assigned a new variable

if(isset($_POST["submit"])) // Here before doing anything we have to check if the button is clicked
{
        $number = rand(1,100); // this contains numbers that will be randomly generated by the system

        $user_input = $_POST["user_input"]; //this will store the information that will be inputted by the user

        if(empty($user_input) || $user_input < 1 || $user_input >100) // If any of the conditions  here is true
        {

            $error_message= "You have to enter a value";  // we will send an error message

           header("location:index.php"); // and we will make sure that  the user doesn't leave the  index page 
                                        // till all of the conditions are false
        
        }
        if($user_input != $number) //if our users get here, the code will check for inequality between users input and system output
        {   
            $winhead="<h2>OOPS Not What you thought</h2>"; // Static h2 tag notifiying user

            $message = "<h3> Your guess $user_input was wrong,system output was $number\n </h3>"; // wrong message  with user input value
                                                                                                  // and system output value

            $succsTitle= "<h2>Don't Give Up</h2>"; //static h2 tag auto generated message title

            $success = $lose; //auto generated qoutes to motivate the users 

        }
        elseif($user_input == $number) //if our users get here, the code will check for equality between users input and system output
        {
            $winhead="<h2>Prediction Hero</h2>"; // Static h2 tag notifiying loosers

            $message = "<h3> You guess $user_input and your guess matched the output from the server $number \n </h3>";// winner message  with user input value
                                                                                                                       // and system output value

            $succsTitle= "<h2>Qoutes For You</h2>"; //static h2 tag auto generated message title

            $success = $win; //auto generated qoutes to motivate the winners 
            
        }
    }

    if(!isset($_POST["submit"]) ) // checking if the user did not click the button
    {
        header("location:index.php"); // taking users to the index page if the condition is true
     }

